learning_note/urls.py
"""learning_note URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
from django.conf.urls import url

   1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import include, re_path
from django.contrib import admin
# from django.views.generic import TemplateView
# from django.conf.urls import url


urlpatterns = [
# path('', TemplateView.as_view(template_name='index.html'), name='index'),
    re_path(r'admin/', admin.site.urls),
    re_path(r'', include('learning_notes.urls', namespace='learning_notes')),
]

learning_notes/urls.py
"""定义learning_notes的URL模式"""
from django.urls import re_path

from . import views
app_name = 'learning_notes'
urlpatterns = [
    # 主页
    re_path('^$', views.index, name='index'),
]

learning_notes/models.py
from django.db import models

# Create your models here.


class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """学到关于特定主题的具体知识"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)


class Meta:
    verbose_name_plural = 'entries'


def __str__(self):
    """返回模型的字符串表示"""
    return self.text[:50] + "..."

learning_notes/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_notes/index.html')

learning_notes/templates/learning_notes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>
    <a href="{% url 'learning_notes:index' %}">Learning Note</a>
</p>
{% block content %} {% endblock content %}
</body>
</html>

learning_notes/templates/learning_notes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learning Notes</title>
</head>
<body>
{% extends "learning_notes/base.html" %}
{% block content %}
<p>Learning Log helps you keep track of your learning, for any topic you're
    learning about.</p>
{% endblock content %}
</body>
</html>